-- Generated by TurASM - DO NOT EDIT

local __turasm_var_table = {}
local __turasm_main = "__turasm_main"
local __turasm_exit = "__turasm_exit"
local __turasm_jmp = "__turasm_main"
local __turasm_cmp = {
  eq = false,
  neq = false,
  lt = false,
  gt = false,
  le = false,
  ge = false,
}

__turasm_var_table["status"] = false
local function __turasm_cmp_func(a, b)
  __turasm_cmp.eq = a == b
  __turasm_cmp.neq = a ~= b
  if type(a) == "number" and type(b) == "number" then
    __turasm_cmp.lt = a < b
    __turasm_cmp.gt = a > b
    __turasm_cmp.le = a <= b
    __turasm_cmp.ge = a >= b
else
    __turasm_cmp.lt = false
    __turasm_cmp.gt = false
    __turasm_cmp.le = false
    __turasm_cmp.ge = false
  end
end

while __turasm_jmp ~= __turasm_exit do
repeat
if __turasm_jmp == __turasm_main then
__turasm_var_table["fuelSlot"] = 0
__turasm_var_table["blockSlot"] = 1
__turasm_var_table["exitmsg"] = "Done!"
__turasm_jmp = "checkFuel"
do break end
__turasm_jmp = "loop"
end
if __turasm_jmp == "loop" then
__turasm_var_table["status"] = turtle.select(__turasm_var_table["blockSlot"])
__turasm_var_table["status"] = turtle.dig()
__turasm_var_table["status"] = turtle.forward()
__turasm_var_table["status"] = turtle.placeDown()
__turasm_cmp_func(__turasm_var_table["status"], true)
if __turasm_cmp.eq then
__turasm_jmp = "checkFuel"
do break end
end
__turasm_var_table["exitmsg"] = "Out of blocks."
__turasm_jmp = "exit"
do break end
__turasm_jmp = "checkFuel"
end
if __turasm_jmp == "checkFuel" then
__turasm_cmp_func(turtle.getFuelLevel(), 0)
if __turasm_cmp.gt then
__turasm_jmp = "loop"
do break end
end
__turasm_var_table["status"] = turtle.select(__turasm_var_table["fuelSlot"])
__turasm_var_table["status"] = turtle.refuel(1)
__turasm_cmp_func(__turasm_var_table["status"], true)
if __turasm_cmp.eq then
__turasm_jmp = "loop"
do break end
end
__turasm_var_table["exitmsg"] = "Out of fuel."
__turasm_jmp = "exit"
do break end
__turasm_jmp = "exit"
end
if __turasm_jmp == "exit" then
print(__turasm_var_table["exitmsg"])
__turasm_jmp = __turasm_exit
end
until true
end

