-- Generated by TurASM - DO NOT EDIT

local __turasm_var_table = {}
local __turasm_main = "__turasm_main"
local __turasm_exit = "__turasm_exit"
local __turasm_jmp = "__turasm_main"
local __turasm_cmp = {
  eq = false,
  neq = false,
  lt = false,
  gt = false,
  le = false,
  ge = false,
}

__turasm_var_table["status"] = false
local function __turasm_cmp_func(a, b)
  __turasm_cmp.eq = a == b
  __turasm_cmp.neq = a ~= b
  if type(a) == "number" and type(b) == "number" then
    __turasm_cmp.lt = a < b
    __turasm_cmp.gt = a > b
    __turasm_cmp.le = a <= b
    __turasm_cmp.ge = a >= b
else
    __turasm_cmp.lt = false
    __turasm_cmp.gt = false
    __turasm_cmp.le = false
    __turasm_cmp.ge = false
  end
end

while __turasm_jmp ~= __turasm_exit do
repeat
if __turasm_jmp == __turasm_main then
__turasm_jmp = "refuel"
end
if __turasm_jmp == "refuel" then
__turasm_var_table["prev"] = turtle.getSelectedSlot()
__turasm_var_table["i"] = 0
__turasm_jmp = "refuelLoop"
end
if __turasm_jmp == "refuelLoop" then
__turasm_var_table["status"] = turtle.select(__turasm_var_table["i"])
__turasm_var_table["status"] = turtle.refuel(1)
__turasm_cmp_func(__turasm_var_table["status"], true)
if __turasm_cmp.eq then
__turasm_jmp = "refuelDone"
do break end
end
__turasm_var_table["i"] = __turasm_var_table["i"] + 1
__turasm_jmp = "refuelLoop"
do break end
__turasm_jmp = "refuelDone"
end
if __turasm_jmp == "refuelDone" then
__turasm_var_table["status"] = turtle.select(__turasm_var_table["prev"])
__turasm_jmp = __turasm_var_table["ret"]
do break end
__turasm_jmp = "main"
end
if __turasm_jmp == "main" then
__turasm_cmp_func(turtle.getFuelLevel(), 0)
__turasm_var_table["ret"] = "main"
if __turasm_cmp.le then
__turasm_jmp = "refuel"
do break end
end
__turasm_var_table["status"] = turtle.dig()
__turasm_jmp = "main"
do break end
__turasm_jmp = __turasm_exit
end
until true
end

