-- Generated by TurASM - DO NOT EDIT

local __turasm_var_table = {}
local __turasm_main = "__turasm_main"
local __turasm_exit = "__turasm_exit"
local __turasm_jmp = "__turasm_main"
local __turasm_ret = "__turasm_main"
local __turasm_cmp = {
  eq = false,
  neq = false,
  lt = false,
  gt = false,
  le = false,
  ge = false,
}

__turasm_var_table["status"] = false
local function __turasm_cmp_func(a, b)
  __turasm_cmp.eq = a == b
  __turasm_cmp.neq = a ~= b
  if type(a) == "number" and type(b) == "number" then
    __turasm_cmp.lt = a < b
    __turasm_cmp.gt = a > b
    __turasm_cmp.le = a <= b
    __turasm_cmp.ge = a >= b
else
    __turasm_cmp.lt = false
    __turasm_cmp.gt = false
    __turasm_cmp.le = false
    __turasm_cmp.ge = false
  end
end

while __turasm_jmp ~= __turasm_exit do
repeat
if __turasm_jmp == __turasm_main then
print("Hello, World!")
print(3)
print(__turasm_var_table["status"])
print({2,3,})
__turasm_var_table["pos"] = {}
__turasm_var_table["pos"]["x"] = 0
__turasm_var_table["pos"]["y"] = 1
__turasm_cmp_func(__turasm_var_table["pos"]["x"], __turasm_var_table["pos"]["y"])
if __turasm_cmp.le then
__turasm_jmp = "lesser"
do break end
end
__turasm_jmp = "greater"
end
if __turasm_jmp == "greater" then
for _=1,__turasm_var_table["pos"]["x"] do
__turasm_var_table["status"] = turtle.up()
end
__turasm_jmp = "end"
do break end
__turasm_jmp = "lesser"
end
if __turasm_jmp == "lesser" then
for _=1,__turasm_var_table["pos"]["y"] do
__turasm_var_table["status"] = turtle.down()
end
__turasm_jmp = "end"
end
if __turasm_jmp == "end" then
__turasm_var_table["status"] = turtle.forward()
__turasm_jmp = __turasm_exit
end
until true
end

