module TurASM.Writer.Prelude ( fileComment 
                             , sectionalize
                             , module TurASM.Writer.Prelude.Var 
                             , module TurASM.Writer.Prelude.Func
                             ) where

import Control.Monad.Writer

import TurASM.Writer.Prelude.Var
import TurASM.Writer.Prelude.Func

fileComment :: Writer String ()
fileComment = tell "-- Generated by TurASM - DO NOT EDIT\n\n"

sectionalize :: Writer String a -> Writer String () 
sectionalize action = do 
    tell ("while " <> jumpVar <> " ~= " <> exitLabel <> " do\n")
    tell "repeat\n"
    void action
    tell "until true\n"
    tell "end\n\n"
